

######NECESSARY PACKAGES###### 
library(ggplot2) #for the function remove missing and for visualizing 
library(truncnorm) # for truncated distrubution for the angles
library(compiler)
library(parallel) #for parallel computation



#ABM functions source
source("/Users/heyyo/Documents/ABM/Script/ABM_functions.R")






scalarproptimeval<- 0.11

##environment parameter
nTree <-200 #number of trees
env_xmin<-0
env_xmax<-2000
env_ymin<-0
env_ymax<-2000

#fruiting parameters
AverageRegenSteps <-18980 #mean time steps for trees to refruit. (365 days=365*13*4=18980)
SdRegenSteps<-00 #sd refruiting time steps

#Trees have 10 fruit slots
#Fruit_p<- rtruncnorm(1, a = 0, b = 1, mean = Fruit_p_mean, sd=Fruit_p_sd)
Fruit_max <- 50 #total number of fruit slots
Fruit_p_mean<-0.2 #Trees have 10 fruit slots. Fruit_p is the probability that a fruit-slot will start growing a fruit. Each tree has it's own fruit probability that is generated by rnorm. Fruit_p_mean is the mean. A higher Fruit_p_mean -> environment with trees that hold more fruits (with a max of 10 fruits per tree each fruiting period)
Fruit_p_sd<- 0.31

steps_to_ripen<- 3120 #In 60 dagen bereikt het fruit een waarde van 100 (value to ripen) -> 13*4*60 = 3120 stappen. Bajinath & Ramcharun, 1983; Eisikowitch, 1968; Piedra-Malagón et al,2019 
decay_start<- 95 #after which ripeness threshold fruit starts to decay.
steps_to_decay<-260 #Niet meer eetbaar na 4 dagen van het rijp worden. Dus na 13*4*4= 208 stappen

#competitor parameter
edibility<-60 #ripeness thresshold from which competitors can eat
visual_det_range<- 100 # (in m) visual detection range for all agents (both agent & primate_agent)
eat_range<-  5 # (in m) distance to an tree from which an agent can start eating (both agent & primate_agent)

#primate parameters
edibilityPrim <- 95
unripe_threshold <- 60 #edibility threshold from which an unripe fruit can be noticed by prim agent.

#memory parameters
#scalarproptimeval<- 0.00 #value between 0-0.2. for the scalar proporty of time. value of 0.2 is inaccurate, while a value of 0.00001 is higly accurate. 
mem_length_ts<- 6240 #number of timesteps that a memory of a location will be kept (before forgetting). #in 90 dagen tijd vergeet de primaat de locatie,.ie. in 120*13*4=6240 stappen- steps_to_forget 
memory_slots<-5 #didnt check if it already works when I use more slots.

return_later<-52 #if agent sees that a remembered tree still contains unripe fruit, it will be in the memory but it will not be a target at that moment.First the prim agent will guess how many steps are needed, but if these steps are less than 1 day, the guess will become 52 steps. 
nr_unripe_threshold<-23 #if a primagent sees a tree with unripe fruits, the tree will need at least this number of fruits to place it in the memory

index_threshold<-26#index threshold when to make a memory a target. this is a half day = 13*4*0.5=26 the index is calculated by guessing the time necessary for a unripe fruit to fruit minus the distance between the agent and the tree. 

#random movement parameters
#stepsize parameters
#rnorm(1, mean = stepmean, sd = stepsd)
stepsize_mean<- 65 
stepsize_sd<- 10

#angle parameters (correlated random walk)
#rtruncnorm(1,a=-359,b=359, mean=0, sd=50)
angle_sd<-50


######CREATING Food_trees######
#Creating locations of food.
Fruit_p= rtruncnorm(1, a=0,b=1, mean = Fruit_p_mean, sd=Fruit_p_sd)
Trees<-NULL







###########run abm multiple times!!!!#########
ABM<-function(iteration){
  
  
  
  ######CREATING Food_trees######
  #Create Trees throughout map
  for(i in 1:nTree){
    Fruit_p= rtruncnorm(1, a=0,b=1, mean = Fruit_p_mean, sd=Fruit_p_sd)
    Tree2 <- data.frame(TreeNo = i, Xcoord = runif(1,env_xmin,env_xmax),Ycoord= runif(1,env_ymin,env_ymax), Regenaration=round(rnorm(1, mean =  AverageRegenSteps, sd=SdRegenSteps)), 
                        fruit_prob = Fruit_p, Fruit_total_90= 0, Regen_counter=0, Fruit_total_95=NA, Unripe=NA,Fruits_created=0)
    Tree2[1,7] <- Tree2[1,4]-sample(x=1:Tree2[1,4],1,replace=T)
    Trees <- rbind(Trees, Tree2)
  }
  
  
  
  #Create Fruits on the Trees
  
  v1 <- cbind( 1-Trees[,5], Trees[,5])
  v1.list <- split(v1, seq(nrow(v1)))
  
  FruitC<-matrix(rep(0,nTree*Fruit_max), nrow=nTree, ncol=Fruit_max) #fruit creating
  FruitC <- t(FruitC)
  
  FruitR<- matrix(rep(1,nTree*Fruit_max), nrow=nTree, ncol=Fruit_max) #ripening
  FruitD<- matrix(rep(100,nTree*Fruit_max), nrow=nTree, ncol=Fruit_max) #decay
  
  Fruits<- array(c(FruitC,FruitR,FruitD), c(nTree,Fruit_max,3))
  
  
  
  
  
  Trees[,6] <- apply(Fruits[,,2]>edibility,1, sum)
  Trees[,8] <- apply(Fruits[,,2]>edibilityPrim,1, sum)
  Trees[,9] <- apply(Fruits[,,2]>unripe_threshold & Fruits[,,2]<edibilityPrim,1, sum)
  
  Trees<- as.matrix(Trees)
  
  
  
  rm(FruitC,FruitD,FruitR,v1.list,v1,Tree2,Fruit_p) #Fruit_p_mean,Fruit_p_sd
  
  
  #starts in the middle of the landscape
  Primate_agent <- cbind(AgentNo = 1, Xcoord = (env_xmax-env_xmin)/2,Ycoord= (env_ymax-env_ymin)/2, eaten=0)
  
  
  #####Dataframe for temporally remembered locations
  #let agent only temporally remember one location
  #how many remembered is added to check
  #target_count is to check how many times something is made a target
  #index value in which it is based whether something is made a target
  Temporal_remembered <-   cbind(RememberedNo = 1:memory_slots, Tree_no= 0, Xcoord = 0,Ycoord= 0,forget_counter=0, target=0,howmany=0, counter_to_ripen=0,target_count=0, index=1000, nr_of_fruits=0)
  
  
  
  
  ######RUN SIMULATION######
  #first simulation with only trees in order for there already to be some ripe fruits when the agents are in the simulations
  #simulations with more than 540 iterations (i.e. average number of steps fruits need to ripen)
  time_steps <- 1500
  Trees_hist<-NULL
  for(ts in 0:(time_steps-1)){
    
    ripeninglist<-fruitripening(Trees,Fruits)
    Trees <- ripeninglist[[1]]
    Fruits <- ripeninglist[[2]]
    
    decaylist<-fruitdecay(Trees,Fruits)
    Trees <- decaylist[[1]]
    Fruits <- decaylist[[2]]
    
    fruitinglist<-fruiting(Trees,Fruits)
    Trees <- fruitinglist[[1]]
    Fruits <- fruitinglist[[2]]
    
    ts   <- ts + 1; 
    Trees_hist[[ts]]<-Trees
  }
  
  
  
  
  
  
  #run the model for 18980 steps (half year = 365*1*13*4) 
  time_steps <- 18980
  Primate_agent_hist  <- NULL; # Here's the list with each location at the time steps
  Trees_hist<-NULL
  Temporal_remembered_hist<-NULL
  
  
  
  #this is in order for determining the angle to take
  Primate_agent_hist[[1]] <- Primate_agent
  Primate_agent_hist[[2]] <- Primate_agent
  
  
  
  ######RUN SIMULATION: PART2######
  for(ts in 2:(time_steps+1)){
    
    
    Temporal_remembered <- Remembertemporal(Primate_agent, Trees, Fruits, Temporal_remembered)
    
    movement_primatelist<- move_primate(Primate_agent, Trees, Fruits, Temporal_remembered, Primate_agent_hist, ts)
    Primate_agent       <- movement_primatelist[[1]]
    Trees               <- movement_primatelist[[2]]
    Fruits              <- movement_primatelist[[3]]
    Temporal_remembered <- movement_primatelist[[4]]
    
    rm(movement_primatelist)
    
    
    Temporal_remembered <- discard_mem(Primate_agent, Trees, Fruits, Temporal_remembered)
    
    
    Temporal_remembered <- forgetting(Temporal_remembered)
    
    
    ripeninglist<-fruitripening(Trees,Fruits)
    Trees <- ripeninglist[[1]]
    Fruits <- ripeninglist[[2]]
    
    rm(ripeninglist)
    
    decaylist<-fruitdecay(Trees,Fruits)
    Trees <- decaylist[[1]]
    Fruits <- decaylist[[2]]
    
    rm(decaylist)
    
    fruitinglist<-fruiting(Trees,Fruits)
    Trees <- fruitinglist[[1]]
    Fruits <- fruitinglist[[2]]
    
    rm(fruitinglist)
    
    ts   <- ts + 1; 
    Primate_agent_hist[[ts]] <- Primate_agent; # Add to list
    Trees_hist[[ts]]<-Trees;
    Temporal_remembered_hist[[ts]]<- Temporal_remembered;
    
  }
  
  
  d<-list(Primate_agent=Primate_agent, Primate_agent_hist=Primate_agent_hist, Trees_hist=Trees_hist, Trees=Trees, Fruits=Fruits, Temporal_remembered=Temporal_remembered,
          scalarproptimeval=scalarproptimeval,steps_to_ripen=steps_to_ripen,edibilityPrim=edibilityPrim,unripe_threshold=unripe_threshold, steps_to_decay=steps_to_decay,
          decay_start=decay_start,Fruit_max=Fruit_max,Fruit_p_mean=Fruit_p_mean,Fruit_p_sd=Fruit_p_sd,nr_unripe_threshold=nr_unripe_threshold, visual_det_range=visual_det_range,
          nTree=nTree,env_xmin=env_xmin,env_xmax=env_xmax,env_ymin=env_ymin,env_ymax=env_ymax,AverageRegenSteps=AverageRegenSteps,SdRegenSteps=SdRegenSteps,edibility=edibility,
          eat_range=eat_range,mem_length_ts=mem_length_ts,memory_slots=memory_slots,return_later=return_later,index_threshold=index_threshold,stepsize_mean=stepsize_mean,
          stepsize_sd=stepsize_sd,angle_sd=angle_sd)
  save(d, file = paste("~/Documents/ABM/Output/model", iteration, ".RData"))
  
}


ABM <- cmpfun(ABM)


d<-as.list(NULL) # name of the list with the data which will be saved.
rtruncnorm <- truncnorm:::rtruncnorm
cores=detectCores()
cl <- makeCluster(cores[1]-1) #not to overload your computer
clusterExport(cl, c("ABM", "rtruncnorm", "anglefun","decay",
                    "discard_mem","distance","forgetting",
                    "fruitdecay","fruiting","fruitripening","move_primate",
                    "move_primate_no_mem",
                    "Remembertemporal","ripen", "scalarpropertyfun",
                    
                    "scalarproptimeval",'steps_to_ripen','edibilityPrim',
                    'unripe_threshold','steps_to_decay','decay_start',
                    'Fruit_max',"Fruit_p_mean","Fruit_p_sd",
                    'nr_unripe_threshold','visual_det_range',
                    "nTree","env_xmin","env_xmax","env_ymin","env_ymax",
                    "AverageRegenSteps","SdRegenSteps", "edibility",
                    "eat_range", "mem_length_ts", "memory_slots",
                    "return_later", "index_threshold",
                    "stepsize_mean", "stepsize_sd", "angle_sd",
                    "Fruit_p", "Trees"
))

#running the model with same settings 40 times over max number of cores -1
parLapply(cl,1:40,function(i) ABM(i[1]))
stopCluster(cl)


#extract the results
for(i in 1:40){
  load(file=paste("~/Documents/ABM/Output/model", i, ".RData"))
  print(c(i,d[[1]][4]))
  rm()
}

